### ISSUE TITLE
Nix Installer adds a superflous newline in `nix.conf` in GitHub Actions

### ISSUE THREAD

**Issue by lucperkins** [DeterminateSystems/nix-installer#135]
I encountered an issue in the Nix Installer GitHub Action where the `access-tokens` config is prefaced with `\n` when written to `nix.conf`:

```conf
\naccess-tokens = *****
```

The basic contours of my Actions configuration:

```yaml
- uses: DeterminateSystems/nix-installer@main
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    extra-conf: |
      binary-caches = https://my-special-cache.org
      trusted-substituters = https://my-special-cache.org
```

I debugged this by adding an Action that `cat`s the config file, which appears to be as expected otherwise.

The offending line seems to be [here](https://github.com/DeterminateSystems/nix-installer/blob/860bc4d040d28fbf7e196ae7cdb0a1fc7b367604/action.yml#L117).
