### ISSUE TITLE
cachix compatibility regression

### ISSUE THREAD

**Issue by josh** [DeterminateSystems/nix-installer#1388]
Using the latest [nix-installer](https://github.com/DeterminateSystems/nix-installer) v0.33.0 via [nix-installer-action](https://github.com/DeterminateSystems/nix-installer-action) paired with [cachix/cachix-action](https://github.com/cachix/cachix-action) on GitHub Actions now crashes due to some permissions or daemon change. 0.32.0 and earlier have worked.

I'm wondering if there was an intentional or unintentional default configuration change between 0.32.0 and 0.33.0?

Reproducible example with failure logs:

https://github.com/josh/nix-installer-issue/blob/bb49b14fa9fd23975d8eea34962f93d61738ef6f/.github/workflows/nix.yml
https://github.com/josh/nix-installer-issue/actions/runs/12777799779/job/35619336920

```yml
name: Nix

on:
  workflow_dispatch:

jobs:
   build:
    strategy:
      matrix:
        source-tag:
          - "v0.31.0"
          - "v0.32.0"
          - "v0.33.0"

    runs-on: ubuntu-latest

    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          source-tag: ${{ matrix.source-tag }}

      - uses: cachix/cachix-action@v15
        with:
          name: josh
          skipPush: true
```
