### ISSUE TITLE
`experimental-features = configurable-impure-env` doesn't work since 0.33 with `extra-conf`

### ISSUE THREAD

**Issue by OlivierLDff** [DeterminateSystems/nix-installer#1390]
Hi, my CI broke with the release 0.33, I guess this is related to https://github.com/DeterminateSystems/nix-installer/pull/1379.

Here is my action:

```yaml
    -
      uses: naostage/nix-installer-action@dea7810afd9d4c98556c8ec68cf361bd5b648eaa
      with:
        extra-conf: |
          experimental-features = configurable-impure-env
          impure-env = NIX_GITHUB_PRIVATE_USERNAME=x-auth-token NIX_GITHUB_PRIVATE_PASSWORD=${{ steps.generate_token.outputs.token }}
```

And when running `nix build` I get:

```
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
```

Current workaround, pin the source tag (that I should have done in the first place)
```yaml
    -
      uses: naostage/nix-installer-action@dea7810afd9d4c98556c8ec68cf361bd5b648eaa
      with:
        source-tag: v0.32.3
        extra-conf: |
          experimental-features = configurable-impure-env
          impure-env = NIX_GITHUB_PRIVATE_USERNAME=x-auth-token NIX_GITHUB_PRIVATE_PASSWORD=${{ steps.generate_token.outputs.token }}
```

I guess this is the same issue as #1389
