### ISSUE TITLE
Setting a `post-build-hook` in the nix config fails

### ISSUE THREAD

**Issue by arianvp** [DeterminateSystems/nix-installer#862]
## The config

```
      - uses: DeterminateSystems/nix-installer-action@main
        with:
         extra-conf: | 
           post-build-hook = ${{ github.workspace }}/post-build-hook.sh
```

The build hook:

```shell
#!/bin/sh

set -eu
set -f # disable globbing
export IFS=' '

# shellcheck disable=SC2086
echo "Uploading paths" $OUT_PATHS
# shellcheck disable=SC2086
exec nix copy --to 's3://cache20240224120542829900000001?region=eu-central-1&secret-key=/tmp/nix-secret-key' $OUT_PATHS
```

## Error

It seems to fail as it calls the build hook before finishing installing nix?

```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `setup_default_profile` errored
   4: Failed to execute command with status 1 `HOME="/root" NIX_SSL_CERT_FILE="/nix/store/sp6cj9vw557zpfirwvvix36p58av82dj-nss-cacert-3.95/etc/ssl/certs/ca-bundle.crt" "/nix/store/vi8vjs4m4dnj5lwgm9p6071m0s7v4p26-nix-2.20.3/bin/nix-env" "-i" "/nix/store/vi8vjs4m4dnj5lwgm9p6071m0s7v4p26-nix-2.20.3"`, stdout: 
      stderr: installing 'nix-2.20.3'
      building '/nix/store/ykahjqw485vhanx3g5wz2q1nk9rrby04-user-environment.drv'...
      running post-build-hook '/home/runner/work/nix-s3-demo/nix-s3-demo/post-build-hook.sh'...
      post-build-hook: Uploading paths /nix
